language: java

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  mvn install --settings .maven.xml --batch-mode -Dmaven.test.skip=true

notifications:
  email: false

cache:
  directories:
  - ~/.m2
